In [14]:
# 9321 2018 S2
import pandas as pd
import numpy as np
#pd.options.display.float_format = '{:,.0f}'.format
'''有打印不出所有 17个 columns的问题.
不确定数字要求是否需要有小数点, 都可以'''

'''Question 1:
Merge the two datasets Olympics_dataset1.csv and Olympics_dataset2.csv and display the first five rows (do not concatenate the datasets).
https://chrisalbon.com/python/data_wrangling/pandas_dataframe_importing_csv/
https://stackoverflow.com/questions/15891038/change-data-type-of-columns-in-pandas
'''

def Question_1():
    summer = 'Olympics_dataset1.csv'
    winter = 'Olympics_dataset2.csv'

    df1 = pd.read_csv(summer,skiprows=1,thousands=',')
    df2 = pd.read_csv(winter,skiprows=1,thousands=',')

    df3 = pd.merge(df1,df2,on='Unnamed: 0')
    df3.rename(columns={'Unnamed: 0':'Country','Total.1':'Total_Medals'},inplace = True)

    df3.apply(pd.to_numeric, errors='ignore')

    df3.astype(int ,errors = 'ignore')
    #df3.to_csv('SumerWinter.csv',sep=',',encoding='utf-8')


    return df3




'''Question 2:
Set the index as the country name and then display the first country in the Dataframe.
https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.set_index.html'''


def Question_2():
    df = Question_1()
    df = df.set_index(['Country'])
    #print(df)
    return df

'''Question 3:
Remove the rubish column and display the first five rows.'''

def Question_3():
    df = Question_1()
    df = df.drop(columns=['Rubish'])
    return df

'''Question 4:
Remove the rows with NaN fields and display the last ten rows.
https://stackoverflow.com/questions/36370839/better-way-to-drop-nan-rows-in-pandas
https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.tail.html` '''

def Question_4():
    df = Question_1()
    df = df.dropna(how = 'any')
    return df


'''Question 5:
Calculate and display which country has won the most gold medals in summer games?
https://chrisalbon.com/python/data_wrangling/pandas_dataframe_importing_csv/
https://chrisalbon.com/python/data_wrangling/pandas_dropping_column_and_rows/
http://www.datasciencemadesimple.com/select-row-maximum-minimum-value-python-pandas/
https://pandas.pydata.org/pandas-docs/version/0.23/generated/pandas.DataFrame.loc.html
'''

def Question_5():
    df = Question_4()
    df = df.drop(df.index[-1])

    #df['Gold_x'].idxmax() return the index of the row where column name "Gold_x" has maximun value
    #df.loc[] return the row of that index
    index = df['Gold_x'].idxmax()
    row = df.loc[index]
    return row

'''Question 6:
Calculate and display which country had the biggest difference between their summer and winter gold medal?
(Print all columns) not just a country name
https://stackoverflow.com/questions/15891038/change-data-type-of-columns-in-pandas
https://pandas.pydata.org/pandas-docs/stable/generated/pandas.to_numeric.html#pandas.to_numeric
https://pythonprogramming.net/pandas-column-operations-calculations/
'''
def Question_6():
    df = Question_4()
    df = df.drop(df.index[-1])
    #df[['Gold_x','Gold_y']].apply(pd.to_numeric)
    df['Gold_Different'] = abs(df.Gold_x - df.Gold_y)
    #print(df)
    index = df['Gold_Different'].idxmax()
    row = df.loc[index]
    return row

''' Question 7:
Sort the countries in descending order, according to the number of total of medals earned throughout the history and display the first and last 5 rows.
http://cmdlinetips.com/2018/02/how-to-sort-pandas-dataframe-by-columns-and-row/
'''
def Question_7():
    df = Question_4()
    df = df.drop(df.index[-1])
    #Method one as below is wrong
    # sortdf = df.sort_values(['Total_x','Total_y'],ascending=False)
    # return sortdf

    #Method two as below
    # df = df.assign(Total_Gold = lambda x: df.Total_x + df.Total_y)
    # df = df.sort_values('Total_Gold', ascending=False)
    # df = df.drop(['Total_Gold'],axis=1)
    # return df

    #Method Three the best
    df = df.sort_values('Total_Medals',ascending = False)
    return df

'''Question 8:
Plot a bar chart of the top 10 countries (according to the sorting in Question 7). For each country use a stacked bar chart showing for each county the total medals for winter and summer games.

'''

def Question_8():
    df = Question_7()
    df = df.head(10)
    df = df.set_index(['Country'])

    #ax = df[['Total.1']].plot(kind='bar', title ="Medals for Winter and Summer Games", figsize=(15, 10), legend=True, fontsize=12)
    #plt.show()



if __name__ == '__main__':


    # print('Question_1 showing as below \n')
    # dfq1 = Question_1()
    # print(dfq1.head(5),'\n')
    #

    #
    # print('Question_2 showing as below \n')
    # dfq2 = Question_2()
    # print(dfq2.head(1),'\n')
    #
    # print('Question_3 showing as below \n')
    # dfq3 = Question_3()
    # print(dfq3.head(5),'\n')
    #
    # print('Question_4 showing as below \n')
    # dfq4 = Question_4()
    # print(dfq4.tail(10),'\n')
    #
    # print('Question_5 showing as below \n')
    # dfq5 = Question_5()
    # print(dfq5,'\n')
    #
    # print('Question_6 showing as below \n')
    # dfq6 = Question_6()
    # print(dfq6,'\n')

    # print('Question_7 showing as below \n')
    # dfq7 = Question_7()
    # print(dfq7.head(5),'\n')
    # print(dfq7.tail(5),'\n')

    
    Question_4()

In [12]:
# 9321 2018 S2
import pandas as pd
import numpy as np
#pd.options.display.float_format = '{:,.0f}'.format
'''有打印不出所有 17个 columns的问题.
不确定数字要求是否需要有小数点, 都可以'''

'''Question 1:
Merge the two datasets Olympics_dataset1.csv and Olympics_dataset2.csv and display the first five rows (do not concatenate the datasets).
https://chrisalbon.com/python/data_wrangling/pandas_dataframe_importing_csv/
https://stackoverflow.com/questions/15891038/change-data-type-of-columns-in-pandas
'''

def Question_1():
    summer = 'Olympics_dataset1.csv'
    winter = 'Olympics_dataset2.csv'

    df1 = pd.read_csv(summer,skiprows=1,thousands=',')
    df2 = pd.read_csv(winter,skiprows=1,thousands=',')

    df3 = pd.merge(df1,df2,on='Unnamed: 0')
    df3.rename(columns={'Unnamed: 0':'Country','Total.1':'Total_Medals'},inplace = True)

    df3.apply(pd.to_numeric, errors='ignore')

    df3.astype(int ,errors = 'ignore')
    #df3.to_csv('SumerWinter.csv',sep=',',encoding='utf-8')


    return df3
s = Question_1()
print(s.head(5))

                    Country Rubish  \
0         Afghanistan (AFG)    BLA
1             Algeria (ALG)    BLA
2           Argentina (ARG)    BLA
3             Armenia (ARM)    BLA
4   Australasia (ANZ) [ANZ]    BLA

   Number of Games the country participated in_x  Gold_x  Silver_x  Bronze_x  \
0                                           14.0     0.0       0.0       2.0
1                                           13.0     5.0       4.0       8.0
2                                           24.0    21.0      25.0      28.0
3                                            6.0     2.0       6.0       6.0
4                                            2.0     3.0       4.0       5.0

   Total_x  Number of Games the country participated in_y  Gold_y  Silver_y  \
0      2.0                                            0.0     0.0       0.0
1     17.0                                            3.0     0.0       0.0
2     74.0                                           19.0     0.0       0.0
3     14.0                                            7.0     0.0       0.0
4     12.0                                            0.0     0.0       0.0

   Bronze_y  Total_y  Number of Games the country participated in.1  Gold.1  \
0       0.0      0.0                                           14.0     0.0
1       0.0      0.0                                           16.0     5.0
2       0.0      0.0                                           43.0    21.0
3       0.0      0.0                                           13.0     2.0
4       0.0      0.0                                            2.0     3.0

   Silver.1  Bronze.1  Total_Medals
0       0.0       2.0           2.0
1       4.0       8.0          17.0
2      25.0      28.0          74.0
3       6.0       6.0          14.0
4       4.0       5.0          12.0